/* @flow */
'use strict'

const GIT_REPO = 'GIT_REPO'
const PACKAGE_JSON = 'PACKAGE_JSON'
const PACKAGE_JSON_DEVDEPS = 'PACKAGE_JSON_DEVDEPS'
const PACKAGE_JSON_NAME = 'PACKAGE_JSON_NAME'

module.exports = {
  GIT_REPO,
  PACKAGE_JSON,
  PACKAGE_JSON_DEVDEPS,
  PACKAGE_JSON_NAME
}
